version: '3.8'

services:
  admin-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: siglat-admin-app
    ports:
      - "2424:80"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:5000}
    networks:
      - siglat-network
    restart: unless-stopped
    depends_on:
      - siglat-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example API service (uncomment and configure if needed)
  # siglat-api:
  #   image: siglat-api:latest
  #   container_name: siglat-api
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - siglat-network

networks:
  siglat-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local